// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgIWrSEOX_6fuZezZUyTWxGiq24J-Fgic',
    appId: '1:666503216611:android:05050ad98929299de634d6',
    messagingSenderId: '666503216611',
    projectId: 'modular-robot-416001',
    databaseURL: 'https://modular-robot-416001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'modular-robot-416001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9q9pe3c27w5qEU9cdqKMURacF8ZxEFr0',
    appId: '1:666503216611:ios:9b266ac3a9389dc0e634d6',
    messagingSenderId: '666503216611',
    projectId: 'modular-robot-416001',
    databaseURL: 'https://modular-robot-416001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'modular-robot-416001.appspot.com',
    androidClientId: '666503216611-odvmk3egmqs7ej4m33dc9ooh7q5fshpf.apps.googleusercontent.com',
    iosClientId: '666503216611-lrgs93faojimqe1bvinekkdaeh321r3v.apps.googleusercontent.com',
    iosBundleId: 'com.teguhharits.bliguh',
  );
}
