// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_KMxPgt4QW44repTVoQ993DGgLruk5ao',
    appId: '1:1034567334569:android:58719c94de6d3718a347b8',
    messagingSenderId: '1034567334569',
    projectId: 'courseguh-5ee3d',
    storageBucket: 'courseguh-5ee3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4dP-jSZIrzCIhMGbNFlegSFFvEcM1LpA',
    appId: '1:1034567334569:ios:8e8810bf76956dbea347b8',
    messagingSenderId: '1034567334569',
    projectId: 'courseguh-5ee3d',
    storageBucket: 'courseguh-5ee3d.appspot.com',
    androidClientId: '1034567334569-fpp7h2qt5999legka07d9372spb0u249.apps.googleusercontent.com',
    iosClientId: '1034567334569-mjvfcemgck7dq97agioeqqfe9829bl3j.apps.googleusercontent.com',
    iosBundleId: 'com.teguhharits.ecommerceFirebaseGetx',
  );
}
