on:
  push:
    branches:
      - release-ui

name: Build My Apps

jobs:
  build:
    name: Build and Release APK and IPA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Build IPA
        run: flutter build ios --release --no-codesign

      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: "13.x" # Set your Xcode version here

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install iOS dependencies
        run: cd ios && pod install && cd ..

      - name: Package and Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v0.2.1
          token: ${{ secrets.TOKEN }}

      - name: Package and Release IPA
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/iphoneos/*.ipa"
          tag: v0.2.1
          token: ${{ secrets.TOKEN }}
